silvia-odwyer/photon

.gitignore, js/index.js, site/src/scripts/demo.js
Thanks for the cool project.
This fixes an issue that causes the demo to only run in Firefox, as Event.originalTarget is only supported there (see https://developer.mozilla.org/en-US/docs/Web/API/Event/originalTarget). 
I also added a basic gitignore.
=> Fix: Demo does only work in Firefox

crate/src/channels.rs, crate/src/colour_spaces.rs, crate/src/multiple.rs
Hi Silvia,
Not sure if `invert` and `mix_with_colour` functions would be useful for this project. Any suggestions are welcomed (code style, implementation, etc.).
=> Invert and mix colour

crate/src/effects.rs
Hi @silvia-odwyer 
Just implemented a very simple contrast adjustment function for RGBA image. I think there must be some much better algorithm, for example, when adjust factor is very close to boundaries (-255.0, 255.0). Hopefully this implementation could be a good start point for you and other developers.
Any advice is welcomed.
=> add contrast

crate/src/channels.rs, crate/src/colour_spaces.rs, crate/src/conv.rs, crate/src/effects.rs, crate/src/helpers.rs, crate/src/lib.rs, crate/src/monochrome.rs, crate/src/multiple.rs, crate/src/native.rs, crate/src/noise.rs, crate/src/transform.rs
https://github.com/silvia-odwyer/photon/issues/29 I have tried to run demo apps, it works and it's compiling with less warnings
=> warnings: removed most of the warnings

crate/src/channels.rs, crate/src/colour_spaces.rs, crate/src/effects.rs, crate/src/iter.rs, crate/src/lib.rs, crate/src/monochrome.rs, crate/src/multiple.rs, crate/src/noise.rs
#36 @silvia-odwyer, please check
=> Image Iterator: writen simple image iterator; O(n)

crate/src/channels.rs, crate/src/colour_spaces.rs, crate/src/conv.rs, crate/src/effects.rs, crate/src/filters.rs, crate/src/lib.rs, crate/src/monochrome.rs, crate/src/multiple.rs, crate/src/native.rs, crate/src/noise.rs, crate/src/text.rs, crate/src/transform.rs
@silvia-odwyer nothing special, it was a bit annoying for me to see so many warnings in IDE
=> docs: fix code samples

.gitignore, crate/examples/add_text.rs, crate/examples/example.rs, crate/examples/seam_carver.rs, crate/src/bin/bin.rs, crate/src/conv.rs, crate/src/effects.rs, crate/src/filters.rs, crate/src/lib.rs, crate/src/multiple.rs, crate/src/native.rs, crate/src/text.rs, crate/src/transform.rs
@silvia-odwyer Hi, I added experimental `seam carver` from imageproc library
* added output image examples into gitignore
* some iterator fixes
* small doc code fixes
=> seam carver: init, also small fixes from before

crate/src/tests.rs
@silvia-odwyer added a simple unit test for Seam Carve
=> seam carve: added unit test

crate/src/effects.rs, site/src/demo.html, site/src/scripts/demo.js, site/src/scripts/script.js
A cool little `oil` effect that lets you turn a picture into an oil painting!
=> Added oil effect

README.md
=> Add build badges to README 

.gitignore, crate/src/channels.rs, crate/src/effects.rs, crate/src/transform.rs
@silvia-odwyer Hi, nothing special small linter fixes; + added react's package-lock into gitignore
=> rust: remove returns, gitignore: react; package-lock

README.md
=> Bump photon-rs version in README.md

crate/src/effects.rs
Just added some extra features for the strips effect. Refactor and new method.
=> Made strips colored

README.md
Made some aesthetic changes to README badges.
=> Updated badges for better look

crate/Cargo.toml
=> added rayon feature which allows to enable or disable rayon dependency

crate/src/channels.rs, crate/src/colour_spaces.rs, crate/src/conv.rs, crate/src/effects.rs, crate/src/lib.rs, crate/src/monochrome.rs, crate/src/multiple.rs, crate/src/noise.rs, crate/src/text.rs, crate/src/transform.rs
bring back `draw_text_with_border` and `draw_text` functions by adjusting a few outdated function calls
=> Re-enable text module

crate/src/multiple.rs
I believe this is all that's required to fix #105. Let me know if I need to add anything else.
=> replace_background takes Rgb by reference

react_app_demo/src/App.css
@silvia-odwyer Hi, soon I will have time and try do some actual work, but for now only small lint fixes
=> react: css; fix small warning that annoys me in ide

crate/src/effects.rs
This PR adds an in-place (i.e. no memory allocation) pixelization effect method with variable pixel size.
=> Add pixelization effect

Cargo.toml, crate/Cargo.toml, crate/src/conv.rs, crate/src/lib.rs
To add blob support this simple function will convert the image to bytes and return a `Uint8Array` that can be written to file
=> Add WASM get_bytes function

crate/src/effects.rs
Resolves https://github.com/silvia-odwyer/photon/issues/98
Dithering is performed via error diffusion algorithm as described [here](https://en.wikipedia.org/wiki/Floyd%E2%80%93Steinberg_dithering).
Alpha-channel is not dithered.
=> Floyd-Steinberg dithering

crate/src/multiple.rs
Fades one image into another.
Supports horizontal, vertical and axial fading.
=> Implement fading

crate/src/tests.rs, crate/src/transform.rs
Simple resampling
* Skip pixels to downsample
* Duplicate pixels to upsample
=> Implement resampling

crate/src/transform.rs
Add a simple compress method to the library based on the solution given in issue #137
If there is a better solution to this lmk, I'd be happy to implement that instead.
Closes #137
=> Add compression method

README.md, crate/src/effects.rs, crate/src/lib.rs
This PR adds duotone effect by replacing the commented-out implementation.
=> Add duotone effect

README.md
- Related to #164 
- Closes #51
=> chore(docs): mention webp

crate/src/multiple.rs
Made a few small changes to update the documentation to mention all currently implemented blend modes and allow for more ways to input a blend mode such as "HARD LIGHT" and "HardLight"
=> Updated multiple.rs

crate/src/monochrome.rs
Hi, this PR fixes the following issue: https://github.com/silvia-odwyer/photon/issues/181.
=> Update monochrome.rs to fix assignment of blue value

crate/src/text.rs
This is kind of a no-brainer.
Instead of height being permanently set to 90, make it a function parameter instead.
=> Text resize

crate/src/text.rs
Not sure the reason for the second image is,
seems unused and me removing it has no bearing on the resulting image for me.
=> Remove dead code
