crate/src/transform.rs
Implemented the cropping and flipping of images (both vertically and horizontally). This partially fixes Issue #3. 
Their corresponding functions have been placed within the `transform` module; this module will contain extra functions such as scaling/rotating/resizing of images in the future. 
However, design decisions may change the current implementation, and several changes in the design may be required before merging to master.
=> Added transform module, which contains cropping and flipping functions. Partially fixes Issue #3

crate/src/lib.rs
Hi Silvia,
just wondering if it was okay to just add `#[wasm_bindgen(constructor)]` to Rgb struct. Then we are able to create an Rgb object in JS like `new module.Rgb(r, g, b)`. For now it's likely we can't pass parameters to constructor. If we call functions such as `set_red` afterwards, a null pointer error raises (`Javascript Error:  Error: null pointer passed to rust`). Tested on Chrome 79.0.3945.88, with latest codes from master branch.
=> add wasm constructor for Rgb struct

crate/Cargo.toml, crate/benches/photon_benchmark.rs, crate/src/conv.rs
Hi Silvia,
I tried to implement a linear-time approximate Gaussian blur algorithm following the introduction to this [link](http://blog.ivank.net/fastest-gaussian-blur.html ). Probably it could be a good complement of current blur functions.
I also wrote a very simple benchmark test based on crate `criterion` (I added it under `dev-dependencies`). The file is in `benches` and you could just run `cargo bench` to see results.
The benchmark only tested two images (`daisies_fuji.jpg` and `underground.jpg`) in `examples` and it showed some performance improvement as follows (hope I didn't make common benchmark mistakes = =):
```
Running target/release/deps/photon_benchmark-6b32e3e6318ed175
Gnuplot not found, using plotters backend
Benchmarking Gaussian Blur/fast_gaussian_blur/0: Warming up for …
```
=> add experimental fast gaussian blur

crate/src/native.rs
removes static lifetime, as it does not allow to use non static variables for path in open_image
=> remove static lifetime

crate/src/lib.rs
Hello Silvia
Here is small patch to add Clone trait to PhotonImage, useful to duplicate images `image_copy = original.clone()`
=> derive Clone trait for PhotonImage

crate/src/multiple.rs
Hi Silvia,
Here is fix for issue #18, the problem was - color first loaded as linear srgba, and then after blending saved as nonlinear srgba
=> Fixed #18 - blend() shifts colors

site/src/scripts/demo.js
I noticed the benchmark time display wasn't rounded, causing the final digits and `ms` text to be cut off sometimes.
This PR makes the time display round to 2 decimal places using [`Number.toFixed()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed).
The choice of 2 digits is a bit arbitrary but it seems like good enough precision to still get the point across 🚀
=> Round benchmark time taken display to 2 decimal places

crate/src/transform.rs
name 'resize_img_browser' is preferable rather than 'resizeimg_browser', don't you think?
And you've already use 'resize_img_browser' at `webpack_demo/js/index.js:74`.
=> fixes method name: 'resize_img_browser' is preferable

webpack_demo/js/index.js
You removed "Base64 Example Demo" and "Vec to PhotonImage Example Demo" in index.html, but index.js held them.
You also removes them from index.js, don't you?
=> fixup webpack demo to include existing image; fixes Issue #35

README.md, crate/Cargo.toml, crate/benches/photon_benchmark.rs, crate/examples/add_text.rs, crate/examples/example.rs, crate/examples/seam_carver.rs, crate/src/bin/bin.rs, crate/src/channels.rs, crate/src/colour_spaces.rs, crate/src/conv.rs, crate/src/effects.rs, crate/src/filters.rs, crate/src/lib.rs, crate/src/monochrome.rs, crate/src/multiple.rs, crate/src/native.rs, crate/src/noise.rs, crate/src/text.rs, crate/src/transform.rs, photon-docs/docs/native-tutorial.md, photon-docs/docs/using-photon-natively.md
For `open_image` the underlying `image` crate actually returns an `enum ImageError` (https://docs.rs/image/0.23.10/image/error/enum.ImageError.html) with errors ranging from an IO error to size, support, etc.
For `save_image` I thought it's more appropriate to have an enum and ask if the `Option` from the `ImageBuffer::from_vec` call should be still `unwrap()`ed or handled with an error as it is now.
1. `struct OpenError` - with `#[transparent]` the `source` of the Error & `impl Display` are delegated to `ImageError` + an implementation of `From<ImageError>` with `#[from]`
2. `enum SaveError` - with `transparent` the `source` of the Error & `impl Display` are delegated to the `std::io::Error`
I am not sure if they should be left like this so feedback is welcome.
1. Find all places of …
=> Feature request: panic-free functions

crate/Cargo.toml, crate/src/effects.rs
This PR ensures that the `halftone` effect uses `&mut PhotonImage` instead of just `PhotonImage`
=> Fix: Halftone consisitency

crate/src/channels.rs, crate/src/colour_spaces.rs, crate/src/conv.rs, crate/src/effects.rs, crate/src/filters.rs, crate/src/helpers.rs, crate/src/monochrome.rs, crate/src/multiple.rs, crate/src/native.rs, crate/src/noise.rs, crate/src/text.rs, crate/src/transform.rs
This PR adds two new native methods to aid with Image Serialization and De serialization.
`open_image_from_bytes`
`save_image_to_bytes`
I have added appropriate Doc fixes for the same. 
Note:
I also removed references to `extern crate` as 2018 edition of Rust advises against their use.
https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html
=> New Native Methods.

photon-docs/docs/native-tutorial.md
According to https://docs.rs/photon-rs/0.2.0/photon_rs/native/fn.save_image.html and https://docs.rs/photon-rs/0.2.0/photon_rs/native/fn.open_image.html
=> Fix in the docs: `expect` isn't necessary today

crate/Cargo.toml, crate/src/effects.rs
I have created a crate for generating [Perlin noise in 2D](https://crates.io/crates/perlin2d), using which I have created the `frosted glass` effect.
```rust
use photon_rs::native::{open_image, save_image};
use photon_rs::PhotonImage;
use photon_rs::effects::frosted_glass;
let mut img = open_image("image.jpg").expect("File not found");
frosted_glass(&mut img);
save_image(img, "image_frosted.jpg");
```
| OriginaI image| Frosted Glass Image|
|------------------|----------------------------|
|![image0](https://user-images.githubusercontent.com/30759667/115706395-392d8c00-a38b-11eb-9cde-54bb8f3af1c9.jpg)|![image0_result](https://user-images.githubusercontent.com/30759667/115706434-4480b780-a38b-11eb-8329-591c16c45952.jpg)|
|![image2](https://user-images.githubusercontent.com/30759667/115706515 …
=> Added a new effect: "Frosted Glass"

crate/Cargo.toml
Imageproc enables rayon as default feature.
Rayon works not well on wasm.
Getting error:
```
panicked at 'The global thread pool has not been initialized.: ThreadPoolBuildError { kind: IOError(Custom { kind: Other, error: "operation not supported on this platform" }) }',
```
This always happens for me, when I add photon-rs to my project and
read a jpeg image using 
```
image::load_from_memory(&data).unwrap();
```
where data is jpeg file data.
=> Disable default features for imageproc dependency

crate/src/effects.rs
Some variables are necessarily borrowed as mutable. I was working on something when this came up as an ide suggestion.
=> Unecessary mut

crate/src/transform.rs
Currently the cropping behaviour always starts at x1 = 0, y1 = 0 on the source image. This should fix that.
=> Get pixels relative to x1 and y1 on source image

crate/src/lib.rs
@silvia-odwyer  hotfix
```
Compiling photon-rs v0.3.1 (/home/horky/Documents/WorkspaceRust/forks/photon/crate)
error[E0308]: mismatched types
--> crate/src/lib.rs:147:21
|
147 |             Clamped(&self.raw_pixels),
|                     ^^^^^^^^^^^^^^^^ types differ in mutability
|
= note: expected mutable reference `&mut [u8]`
found reference `&Vec<u8>`
error[E0308]: mismatched types
--> crate/src/lib.rs:354:17
|
354 |         Clamped(&new_image.raw_pixels),
|                 ^^^^^^^^^^^^^^^^^^^^^ types differ in mutability
|
= note: expected mutable reference `&mut [u8]`
found reference `&Vec<u8>`
error[E0308]: mismatched types
--> crate/src/lib.rs:420:57
|
420 |     ImageData::new_with_u8_clamped_array_and_sh(Clamped(&raw_pixels), width, height)
| …
```
=> HOTFIX: fix clamped mut

README.md, crate/src/effects.rs
This PR adds image normalization (aka. contrast stretching). The process does not require any dynamic memory allocation and floating-point arithmetics.
=> Add image normalization

README.md, crate/src/colour_spaces.rs
This PR adds gamma correction function by rewriting previously commented-out implementation. Even if we don't include the fact that previously used `DynamicImage` overhead, the current implementation should be still faster. Only gamma lookup tables are allocated dynamically (3x256 bytes).
See: #111
=> Add gamma correction function

crate/examples/example.rs, crate/examples/seam_carver.rs, crate/src/bin/bin.rs, crate/src/native.rs
This PR;
1. Merges `native::OpenError` and `native:SaveError` into `native::Error`.
2. Modifies `save_image` to be a panic-free function (with an exception, see 3rd point).
3. Removes `BufferSize` error. Because previously implemented `native::SaveError::BufferSize` error does not make sense. It was related to incorrect argument passing for `ImageBuffer::from_vec` function. This should raise a panic and shouldn't be related to the user input.
4. Updates relevant call sites.
See: #28
=> Merge open and save errors into a single error type

crate/src/conv.rs
Override radius value in order to avoid exceeding image bounds.
Resolves https://github.com/silvia-odwyer/photon/issues/59.
=> Resolve panic in Gaussian blur

crate/src/transform.rs
An attempt to resolve https://github.com/silvia-odwyer/photon/issues/117.
The idea of this implementation:
* Delegate 90/180/270/360 degree rotation to `image::imageops::rotate90`.
* Move coordinate origin to the centre of the input image.
* Do rotation via [rotation matrix](https://en.wikipedia.org/wiki/Rotation_matrix#In_two_dimensions).
=> Naive implementation for image rotation

.github/workflows/ci.yml, .github/workflows/compile_wasm.yaml, crate/src/lib.rs
- This PR adds saving_jpeg bytes support with quality and also fixes to_bytes as there was an error with the code.
- I've also added a GH action that compiles the WASM code and saves it to a seperate branch to allow dev installs with 
```
npm add https://github.com/silvia-odwyer/photon#compiled-wasm
```
This is great for testing and development.
=> chore: fix to_bytes and add jpeg_saving support

README.md, crate/src/channels.rs
This PR adds selective colorization effect by replacing the commented-out implementation. Please note that the new implementation mixes the colors of matched pixels rather than the reference color compared to the old implementation. Mixing with the reference color produces hard transitions around matched area boundaries whatever `fraction` value is provided. The new implementation helps smooth transitions around matched areas with low `fraction` values.
=> Add selective colorization

crate/Cargo.toml, crate/src/channels.rs, crate/src/colour_spaces.rs, crate/src/conv.rs, crate/src/effects.rs, crate/src/filters.rs, crate/src/helpers.rs, crate/src/lib.rs, crate/src/monochrome.rs, crate/src/multiple.rs, crate/src/text.rs, crate/src/transform.rs
> **TL;DR:** use the feature `enable_wasm = false` to skip compilation of all WASM-only dependencies and functionality.
Some users may wish to make use of the excellent filters and image processing in a pure Rust project. In these cases, they can avoid the build time and overhead from WASM dependencies, like in the case of #147. Providing a single feature flag `enable_wasm = false` makes this very convenient for them.
Sometimes Photon is used as a dependency of another package that itself is compiled into WASM, like in the case of [`hypetrigger`](https://github.com/nathanbabcock/hypetrigger). There is no such thing as tree-shaking the compiled WASM bundle (yet), and the full-size Photon bundle can be relatively large and include methods that are never used in the downstream library. The …
=> Add `enable_wasm` crate feature

crate/src/conv.rs
Applying some of these convolution filters to a fully opaque image will set the alpha channel to full transparent, as described here: https://stackoverflow.com/a/70429242
With this approach, when the image would be rendered fully transparent (all alpha values are 0), restore the alpha to the original value.
=> #145 - Some convolution filters are not working

crate/src/lib.rs, crate/src/noise.rs, crate/src/transform.rs
This PR adds the ability to compile for `wasm32-wasi` target. I was attempting to build an app using [Spin](https://github.com/fermyon/spin). An example application can be found [here](https://github.com/karthik2804/photon-image).
I am happy to update CI to test for the `wasm32-wasi` target as well.
=> Add support building for `wasm32-wasi` targets.

README.md
Many of us want to use Photon with Cloudflare Workers. However, neither [@silvia-odwyer/photon](https://www.npmjs.com/package/@silvia-odwyer/photon) nor [@silvia-odwyer/photon-node](https://www.npmjs.com/package/@silvia-odwyer/photon) works on Cloudflare Workers.
To address this issue, I have published an NPM package [@cf-wasm/photon](https://www.npmjs.com/package/@cf-wasm/photon) that is compatible and works well on Cloudflare Workers. I would like to add this information in the README so that users can easily find and utilize it.
=> Library for Cloudflare Workers

.gitignore, crate/Cargo.toml, crate/examples/example.rs, crate/examples/seam_carver.rs, crate/src/bin/bin.rs
I did this PR because I have issues with a personnal project, i hope you will soon merge it :)
=> Make it not require a specific version of dependency "wasm-bindgen"

crate/src/lib.rs
closes: #171
This is a very basic **approximate** file size estimation from base64 representation of the image.
added this since i needed a way to get approx file size to do further optimizations on the image.
=> Estimated filesize calculation

crate/src/conv.rs
This pull request implements a sobel filter using the magnitude of the X and Y components of the sobel filter to build the image. It calculates $\sqrt{X^2 + Y^2}$ for each pixel of the image, with X the horizontal sobel component, and Y the vertical sobel component.
It was discussed in the related issue ( closes #192 ) that tests were written in `tests.rs`, but calculating the expected result would just come to applying the algorithm by hand. As I noticed that none of the other convolution functions had a test, should I still write a test for it ?
I modified `src/bin/bin.rs` quickly to test the result:
Original image:
Global sobel:
For comparison, here are both the horizontal and vertical sobel:
Horizontal          |  Vertical
:-------------------------:|:-------------------------:
As a …
=> Sobel on both X and Y

crate/src/lib.rs
Currently there's no public method to read the bytes of the pixel data without cloning, this is very inefficient for large images.
=> add raw pixel slice method
